erDiagram

%% ENTITIES
**Space** {
	VARCHAR(10) space_id PK
	NVARCHAR(30) space_name
	TINYINT space_type_id FK
	CHAR building
	TINYINT floor
	TINYINT room_number
	INT capacity
	TINYINT space_status_id FK
	NVARCHAR(200) policy
}

**User** {
	VARCHAR(8) user_id PK
	NVARCHAR(30) surname
	NVARCHAR(20) given_name
	NVARCHAR(255) email UK
	VARCHAR(10) phone_number UK
	TINYINT user_role_id
	TINYINT department_id
	VARCHAR(10) status
}

**Facility** {
	TINYINT facility_type_id PK, FK
	INT facility_sequence_number PK
	NVARCHAR(30) facility_name
	VARCHAR(10) space_id FK
}